version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: pnpm run start:dev
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: chat_app
      MYSQL_USER: kuroneko
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
