version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    command: pnpm run start:dev
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: chat_app
      MYSQL_USER: kuroneko
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db-store:/var/lib/mysql
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './db/setup.sql:/docker-entrypoint-initdb.d/setup.sql'

volumes:
  db-store:
