name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: env
        run: |
          cp .env.development.example .env.development.local
          cp .env.test.example .env.test.local

      - name: up
        run: docker compose up -d

      - run: corepack enable

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: install
        run: pnpm install --frozen-lockfile

      - name: test
        run: make testing
