name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: env
        run: |
          cp .env.development.example .env.development.local
          cp .env.test.example .env.test.local

      - name: up
        run: docker compose up -d

      - name: setup
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 9.12.0

      - name: install
        run: pnpm install

      - name: test
        run: make testing
