name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: env
        run: |
          cp .env.development.example .env.development.local
          cp .env.test.example .env.test.local

      - name: up
        run: docker compose up -d

      - name: test
        run: make testing
